# hexo-theme-miho
# https://github.com/wongminho/hexo-theme-miho

# Favicon of your site | 网站icon
favicon: //cdn.ru23.com/img/favicon.ico

# Header

# Keywords of your site | 网站关键字
keywords: 前端迷,前端开发,前端知识大全,前端优化,前端导航,小程序,ru23.com,JavaScript,ajax,angular,css,webpack,react,gulp,htmlhtml5,mocha,nginx,node,css3,vue,vue-cli,scss
# Head headline | 头部标题
header_title: 前端迷
# Head description | 头部描述
header_description: 凡事预则立，不预则废
# Link to your logo | logo地址
logo: //cdn.ru23.com/img/images/chrome.png
# Link to your banner_img | 首页banner图地址
# banner_img: //cdn.ru23.com/img/images/banner.jpg
banner_img: https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302
# Menu setting | 菜单设置
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Title | 标题
#    url: //minhow.com    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
menu:
  heart:
    title: 前端社区
    url: https://58fe.com
    target: true
  home:
    title: 主页
    url: /
    target: false
  archive:
    title: 归档
    url: /archives
    target: false
  # list-ol:
  #   title: 阅读排行
  #   url: /top
  #   target: false
  #th-list:
  #title: 目录
  #url: /categories
  #target: false

# Social setting, use to display social information | 社交设置，用来展示社交信息
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Icon title | 图标标题
#    url: //minhow.com    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
social:
  wechat:
    title: 公众号
    url: https://mp.weixin.qq.com/s/K3yG4eyuQvZxXIU9jas8kA
    target: true
    icon: mp
  juejin:
    title: 掘金
    url: https://juejin.im/user/57fb24cf816dfa0056c1f8af
    target: true
    icon: juejin
  github:
    title: Github
    url: //github.com/ru23
    target: true
    icon: github
  zhihu:
    title: 知乎
    url: https://www.zhihu.com/people/58fe/activities
    target: true
    icon: zhihu
# weibo:
# title: Weibo
#  url: //weibo.com/WongMinHo
# target: true
# twitter:
# title: Twitter
# url: //twitter.com/huangminhow
#target: true
#qq:
#weixin:
#snapchat:
#telegram:
#envelope-o:
#facebook:
#google:
#linkedin:

# Content

# Excerpt length | 摘录长度
excerpt_length: 100
# Excerpt link | 摘录链接
excerpt_link: 阅读全文>>
# New window open link | 新窗口打开文章
open_new_link: true
# Article default cover picture，size：350*150 | 文章默认封面图，尺寸：350*150
cover_picture: https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302
# Open background particles | 开启背景粒子
open_bg_particle: false
# Open animation in homepage and head | 开启主页及头部动画
open_animation: false

# Article

# Open toc | 是否开启toc
toc: true
# Open share | 是否开启分享
share: true

# Style customization | 样式定制
style:
  # Main color tone | 主色调
  main_color: "#0cc"

# Reward | 打赏

reward:
  # 0-close, 1-All articles are rewarding, 2-Article's md file has reward:true attribute, only reward
  # 0-关闭, 1-所有文章均有打赏, 2-文章的md文件里有reward:true属性，才有打赏
  status: 2
  # 标题
  title: 请我吃糖~
  # 微信，关闭设为 false
  wechat: //cdn.ru23.com/img/images/wechat_code.jpg
  # 支付宝，关闭设为 false
  alipay: //cdn.ru23.com/img/images/alipay_code.jpg

# Comments | 评论

# 畅言，输入appid和appkey
changyan_appid: false
changyan_appkey: false
# 友言，输入id
youyan_id: false
# disqus
disqus: false
# gitment  https://github.com/imsun/gitment
gitment:
  owner: false #你的 GitHub ID
  repo: "" #存储评论的 repo
  client_id: "" #client ID
  client_secret: "" #client secret
# Valine Comment system. https://valine.js.org
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId: OOiJvCREqswvpnTL4RuSShLq-gzGzoHsz
  appKey: OPfVBB2YjMrT3ngcc8mu6w8g
  notify: true # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 输入评论... # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size
# Analytics | 分析
# 站长分析，输入站点id
cnzz_analytics: 1275440747
# 百度分析，输入key值
baidu_analytics: false
# google analytics | google分析
google_analytics: false

# Footer

# Access statistics | “不蒜子”访问量统计
access_counter:
  on: true
  site_uv: 总访客数：
  site_pv: 总访问量：

# Copyright Information | 版权信息
copyright: 2015-2020 frank

aside:
  aliyun:
    title: "阿里云双十二大促，新老用户皆可返现"
    tip: "阿里云双十二大促，新老用户皆可返现"
    img: "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
    url: "https://www.aliyun.com/minisite/goods?userCode=jh5fwy2j&share_source=copy_link"
  tencent-cloud:
    title: "【腾讯云】云产品采购季，助力行业复工。1核2G云服务器，首年99元"
    tip: "【腾讯云】云产品采购季，助力行业复工。1核2G云服务器，首年99元"
    img: "https://upload-dianshi-1255598498.file.myqcloud.com/345x200-c37e147ab2b4b8074e63d71ca21420cf1a7d4933.png"
    url: "https://cloud.tencent.com/act/cps/redirect?redirect=1067&cps_key=3bd05bbfb4f3f97d7bb5964ef12edda9&from=console"
  wechatmp:
    title: "微信公众号：前端迷"
    img: "//cdn.ru23.com/hexo/public/wechat-mp.png"
  wechat-group:
    title: "微信前端技术交流群"
    img: "//cdn.ru23.com/hexo/public/group.png"
  ad-more:
    tip: "广告位出售，日ip100+，联系vx:qianduanmi,备注广告，价格5元/月，随时上线"
    img: " https://cdn.ru23.com/common/sale.png"
